<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net451</TargetFramework>
    <UserSecretsId>66a7f119-cb02-4d1c-9dea-e02162020fa6</UserSecretsId>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Lightning">
      <HintPath>..\..\..\ModdedLightning.exe</HintPath>
    </Reference>
    <Reference Include="MMHOOK_ModdedLightning">
      <HintPath>..\..\..\MMHOOK_ModdedLightning.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>..\..\..\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>..\..\..\MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>..\..\..\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="YamlDotNet">
      <HintPath>..\..\..\YamlDotNet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
